### ISSUE TITLE
.env keys and values with `$` are not parsed

### ISSUE THREAD

**Issue by shazron** [adobe/aio-lib-core-config#27]
### Expected Behaviour

A line with an escaped `$` character should be read into the environment.

### Actual Behaviour

A line with an escaped `$` character is not read into the environment.

### Reproduce Scenario (including but not limited to)

Put this into an .env file:
```
AIO_\$ims=foo
```

Observe that `process.env.AIO_$ims` is undefined.

**Comment by shazron** [comment]
We are using `dotenv` to parse the .env file. The regular expression needs to be updated to:
`const RE_INI_KEY_VAL = /^\s*([\w.-\\$]+)\s*=\s*(.*)?\s*$/` 

The line affected: https://github.com/motdotla/dotenv/blob/e8744104cd3c8b87d258dc153f72b5216ecb4fac/lib/main.js#L32

**Comment by shazron** [comment]
Closed with #28. This is a temporary patch until we can patch `dotenv` itself.

**Comment by alexkli** [comment]
Environment variable names don't support special chars like `$`, see https://stackoverflow.com/questions/2821043/allowed-characters-in-linux-environment-variable-names, that's why `dotenv` is not supporting these.

In Bash:
```
> export TEST\$VAR=hallo
bash: export: `TEST$VAR=hallo': not a valid identifier

> export TEST\\$VAR=hallo
bash: export: `TEST\=hallo': not a valid identifier
```

Is there a need for this?

I am asking because this little change makes this library extremely big as it pulls in `patch-package` which makes up 6.2 MB out of 6.6 MB total cost of `@adobe/aio-lib-core-config` and pulls in over 200 extra libraries of all kinds, which should not be needed at all for a config reading library.

**Comment by shazron** [comment]
This is currently needed for the ims config (.env variables needed to have credentials from the downloaded Dev Console project mapped to aio config) which unfortunately uses a `$` prefix (`$ims`). See the example config: https://github.com/adobe/aio-lib-ims

I've already discussed this with Jesse regarding changing this, and we want to change this but didn't have time without impacting everything. This will be a breaking change, but since we are at Developer Preview this change wouldn't be a big impact if we change now.

**Comment by purplecabbage** [comment]
Yeah. This needs some priority. I didn’t realize the size of the change to config-lib ...
This impacts every core plugin.

**Comment by fmeschbe** [comment]
>  I didn’t realize the size of the change to config-lib ...

Well, one could state that using such a huge library and dependencies for such little effect is overkill ;-)

But I get the point. Let's consider why `$` has been used as a prefix in the first place, and fix that problem going forward.

`$` was chosen as a prefix to internal names such as `$ims`, `$current`, and `$plugins`. As a side-effect this knowledge is also leveraged to filter the `$current` and `$plugins` properties out of the context listing.

On option would be to restructure the config as follows:

```
{
  "ims": {
    "config": {
      "plugins": [ "p1", "p2" ],
      "current": "sample"
    },
    "contexts": {
      "sample": {},
      "another": {}
    }
  }
}
```

This is just a thought, apart from migration concerns which must be taken care of, I am not really hung up to this.

**Comment by meryllblanchet** [comment]
@shazron @purplecabbage are you fine with @fmeschbe 's proposal or do you have other suggestions?

If so I'm also in for solving this with a high priority. We should also have a clear documented migration approach for the users that would be impacted.

**Comment by shazron** [comment]
+1 on Felix's proposal

**Comment by alexkli** [comment]
Yeah, apart from the size issue (which is just due to the way the patching of dotenv is done, and could probably be done more lightweight) it‘s probably not ideal to use a character in environment variables that is usually not supported (even if this is only somewhat indirectly IIUC). It would probably create issues in other tools/libraries than dotenv as well.

If that is addressed, and the standard dotenv library can be used again, the size issue is automatically resolved as well from what I can see.

**Comment by shazron** [comment]
Changes will be part of https://github.com/adobe/aio-cli/issues/191
